CREATE TABLE reset_tokens
(
    user_id INT PRIMARY KEY NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    reset_token VARCHAR(200) NOT NULL UNIQUE,
    created_At TIMESTAMP NOT NULL DEFAULT NOW()
)